server:
  port: 8980
  
spring:
  # Database configuration
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:postgis}
    username: ${DB_USER:postgis}
    password: ${DB_PASSWORD:postgis}
  # JPA configuration  
  jpa:
    hibernate:
      ddl-auto: update
      # Avoid issue with JPA case insensitive
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # This should no longer be needed with Hibernate 6
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect  #org.hibernate.dialect.PostgreSQLDialect  # org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect 
    show-sql: true
    database: postgresql
    # PotGIS configuration
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        jdbc: 
          lob:
            non_contextual_creation: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace